apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transformer
  name: transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
    spec:
      hostname: transformer
      containers:
        - name: transformer
          image: racelab/depot-transformer:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--depot-endpoint=http://manager.default:8888"
            - "--depot-access-key=$(CLUSTER_TOKEN)"
          env:
            - name: CLUSTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cluster-credentials
                  key: token
                  optional: false
          ports:
            - containerPort: 9994
          resources:
            requests:
              memory: 4000Mi
              cpu: 1500m
            limits:
              memory: 4000Mi
              cpu: 1500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: transformer
spec:
  clusterIP: None
  ports:
    - port: 9994
      targetPort: 9994
  selector:
    app: transformer